// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<main.Status>;

export function OpenLogDir():Promise<void>;

export function Quit():Promise<void>;

export function Retry():Promise<void>;
