// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Retry() {
  return window['go']['main']['App']['Retry']();
}
